# This config file is used by gazebo
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    dbot_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dbot_arm_controller:
  ros__parameters:
    joints:
      - j0_joint
      - j1_joint
      - j2_joint
      - j3_joint
      - j4_joint
      - j5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity